# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nikhil Kandukuri
title: MS CS (IIS) Graduate Student at Carnegie Mellon University
email: nikhilkandukuri@cmu.edu
mobile: +1 (878)-834-9329
website: https://nikhil-kandukuri.github.io/


# Dark Mode (true/false/never)
darkmode: false

# Social links
# linkedin_username: nikhil-kandukuri-b78487202
# orcid_username: 0000-0000-0000-0000
github_username: Nikhil-Kandukuri 

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/test.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm a current graduate student at Carnegie Mellon University. 
  
  Possess two years of IT Experience working with the latest tech stack like Quarkus , gRPC , Google Pub/Aub , Debezium at Deutsche Bank.  

  Interned at MNCs like Samsung Research and Western Digital where I applied my skills of academia in some enriching projects centred around Bixby ( Samsung's Voice Assistant) and the new generation of flash drives.

  I am currently pursuing research in the space of event temporal extraction using LLMs. Have made a paper submission to NAACL 2024 as a co-author. 
  Excited to explore further in the field of Mahcine Learning and Natural Language Processing!

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Carnegie Mellon University
        caption: Aug 2023 - Dec 2024
        sub_title: Master of Science in Computer Science (IIS)
      - layout: top-middle
        title: BITS Pilani
        caption: Aug 2017 - Jul 2021 (CGPA - 9.29/10)
        sub_title: Bachelors of Engineering in Electrical and Electronics Engineering
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Deutsche Bank
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Analyst
        caption: July 2021 - June 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            • Played a key role in the development team that built the Cash Settlement Engine' product for the Investment
            Banking Division
            
            • The project's aim was to replace existing five monolithic settlement systems with a modernistic cloud hosted
            micro-service based architecture acting as a unified settlement system across various products
            
            • Cash Settlement Engine will save 5 million euros annually by decommissioning current vendor products
            
            • Implemented key software strategies including Domain Driven Design, Event Driven Architecture, and Test Driven
            Development with code coverage exceeding 80%, and Behavior Driven Development with a 100% Passing Serenity BDD report
    # content:
      - layout: left
        title: Samsung Research Institute
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Associate
        caption: Jan 2021 - June 2021
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            • Worked in the Voice Intelligence R&D team focused on Automatic Speech Recognition.
            
            • The outcome of the project was to enhance end to end Automatic Speech Recognition systems using data augmentation
            techniques.
            
            • Worked with a variety of NLP frameworks related to speech recognition, synthesis, sampling, filtering and translation
    # content:
      - layout: left
        title: Western Digital
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Intern
        caption: May 2020 - July 2020
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            • At Western Digital I worked with the Firmware group in the RPG(Removable Product Group) department. The project was based in Data Analytics.
            
            • The teams used .map files for observing patterns in the firmware. However, many crucial components were being looked at manually leading to inefficiencies in performance.
            
            • The tool I developed parsed data from these files and converted them into a ubiquitous format, supporting SQL queries.
      
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Neural Architecture Search for Skin Cancer Detection 
        sub_title: Research Project UC San Diego
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  Neural Architecture Search for Skin Cancer Detection 
            # icon: fab fa-github
            url: https://www.researchgate.net/publication/355292507_Neural_Architecture_Search_For_Skin_Cancer_Detection
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Enhanced diagnosis of early stages of skin cancer using the method of Neural Architecture Search (NAS), improved by the technique of Learning by Passing Tests (LPT) to improve accuracy by close to 1%
          
          The experiments consisted of two models, a teacher model, and a learner model, mirroring processes occurring in human learning

          [Link to Preprint](https://www.researchgate.net/publication/355292507_Neural_Architecture_Search_For_Skin_Cancer_Detection)
      - layout: top-middle
        title: Event Temporal Ordering using LLMs
        sub_title: Research Project Carnegie Mellon University
        # link: github.com/sproogen
        # link_text: Project Website
        # quote: >
      
        description: | # this will include new lines to allow paragraphs
          Directed benchmarking Large Language Models (LLMs) on event ordering temporal tasks for four 
          existing datasets through prompt engineering and evaluated performance models encompassing LLaMa (7B,13B,70B) , 
          Flan-T5(3B,XL,XXL)
      - layout: top-middle
        title: Text Injection for Automatic Speech Recognition (ASR)
        sub_title: Research Project Carnegie Mellon University
        # link: github.com/sproogen
        # link_text: Project Website
        # quote: >
      
        description: | # this will include new lines to allow paragraphs
          Experimented bolstering ASR performance through representative alignment of text and speech 
          upsampling text by a factor of 4 using contrastive loss a predominant technique in multimodal research
          
  - title: Awards and Acievements
    layout: text
    content: | # this will include new lines to allow paragraphs
      <mark>Academic Merit Scholarship</mark>: Received scholarship for four semesters during my Undergraduate Degree, awarded based on GPA to the top performing 3% of the undergraduate cohort of close to 1100 students
      
      <mark>Concours Romain Rolland</mark>: Third Rank All India under the B1 category (French Olympiad)
      
      <mark>Deutsche Bank Global Hackathon</mark>: Declared as the best team from India for building an application promoting mental health
      
      <mark>Deutsche Bank Recognition Award</mark>: Awarded the DBRecognition award for the first quarter of 2023 for migrating the Cash Settlement Engine from development to User Acceptance Testing (UAT).


  - title: Technical Skills and Courses
    layout: text
    content: | # this will include new lines to allow paragraphs
      <mark>OS</mark>: Windows, Linux

      <mark>Programming Languages</mark>: Python, Java, C++, C

      <mark>Libraries</mark>: Gensim, OpenCV, TensorFLow, Kaldi, Espnet, Scipy, Scikit, Keras, Pytorch

      <mark>Skills</mark>: CI/CD , Kubernetes, gRPC , Test Driven Development, SQL, PostgreSQL, Google Pub/Sub , Agile, Event Driven Architecture, Debezium

      <mark>Subjects</mark>: Machine Learning, Artificial Intelligence, Neural Networks and Fuzzy Logic, Python Programming, Information Retrieval, Foundations of Data Science, Data Structures and Algorithms, C programming, Probability and Statistics, Operating Systems
      Object Oriented Programming, Digital Design, Optimization, Applied Statistical Methods, Generative AI, Multimodal Machine Learning, MLOps, Advanced Natural Language Processing, Speech Recognition and Understanding
      
      <mark>Languages</mark>: English, Telugu, Hindi, French
  # - title: Awards and Acievements
  #     layout: text
  #     content: | # this will include new lines to allow paragraphs
  #       Academic Merit Scholarship: Received scholarship for four semesters during my Undergraduate Degree, awarded based on GPA to the top performing 3% of the undergraduate cohort of close to 1100 students
  #       | Concours Romain Rolland: Third Rank All India under the B1 category (French Olympiad)
  #       | Deutsche Bank Global Hackathon: Declared as the best team from India for building an application promoting mental health
  #       | Deutsche Bank Recognition Award: Awarded the DBRecognition award for the first quarter of 2023 for migrating the Cash Settlement Engine from development to User Acceptance Testing (UAT).

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
